version: '3.8'

services:
  app:
    build: .
    container_name: dev-challenge-app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development